workflow: fix condition

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -25,4 +25,4 @@ jobs:
           echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
       - if: steps.publish.outputs.type == 'none'
         run: |
-          echo '::warning:: current package tag already published to registry.'
+          echo "::error:: current package tag already published to registry." && exit 1
